/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SI3;

import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author piotr
 */
public class Window extends javax.swing.JFrame {

    private JButton tab[][];
    private FieldListener listener;
    public int counter1 = 0;
    public int counter2 = 0;
    public int tabSize;
    private Game game;

    public Window() {
        startNewGame();
    }

    public void startNewGame(){
        initComponents();
        
        JOptionPane panel = new JOptionPane();
        String promptInt = panel.showInputDialog("Type size of your board, but less than 129:");
        
        tabSize = Integer.parseInt(promptInt);
        if (tabSize > 128) {
            tabSize = 128;
        }
        setTitle(getTitle() + " " + tabSize + "x" + tabSize);

        tab = new JButton[tabSize][tabSize];
        listener = new FieldListener();
        generateBoard();
        game = new Game(tab, counter1Label, counter2Label);
        listener.setGame(game);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        counter1Label = new javax.swing.JLabel();
        gamer1Label = new javax.swing.JLabel();
        gamer2Label = new javax.swing.JLabel();
        counter2Label = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SI MKanak 206906");
        setBackground(new java.awt.Color(0, 0, 0));

        counter1Label.setText("0");

        gamer1Label.setText("Player 1");

        gamer2Label.setText("Player 2");

        counter2Label.setText("0");

        jButton1.setText("AUTO SI");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gamer1Label)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(counter1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(counter2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(gamer2Label))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(0, 61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gamer1Label)
                    .addComponent(gamer2Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(counter2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(counter1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.game.autoTurn();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    private void generateBoard() {
        for (int i = 0; i < tabSize; i++) {
            for (int j = 0; j < tabSize; j++) {
                JButton b = new JButton();
                b.setBounds(60 + (25 * j), 90 + (25 * i), 30, 30);
                b.addActionListener(listener);
                this.add(b);
                tab[i][j] = b;
            }
        }
        
        if (tabSize > 6) {
            this.setBounds(0, 0, 90 + (tabSize * 30), 120 + (tabSize * 30));
        } else {
            this.setBounds(0, 0, 120 + (tabSize * 30), 180 + (tabSize * 30));            
        }
        this.setLocation(400, 400);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel counter1Label;
    public javax.swing.JLabel counter2Label;
    private javax.swing.JLabel gamer1Label;
    private javax.swing.JLabel gamer2Label;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
